# src-tauri/permissions/scan-folder.toml
"$schema" = "../gen/schemas/schema.json"

[[permission]]
identifier = "scan-folder"
description = "allow commands for FileExplorer"
commands.allow = ["scan_folder", "add_folder", "add_md_file", "delete_node"]
